src/auroralite/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("slides.urls", namespace='slides')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/slides/urls.py
from django.conf.urls import url

from .views import (slides_contents, slide_topics, slide_stack, search)

urlpatterns = [
    url(r'^$', slides_contents, name='slides_contents'),
    url(r'^search/$', search, name='search'),
    url(r'^(?P<topic>[\w|\s]+)/$', slide_topics, name='slidetopics'),
    url(r'^(?P<topic>[\w|\s]+)/(?P<slug>[\w-]+)/$', slide_stack, name='slidestack'),
]

src/slides/models.py
from django.db import models
from django.utils.text import slugify
from django.utils import timezone
import re


class SlideStack(models.Model):
    """
    A SlideStacks is a "container" for slides. It manages a set of slides of the same affiliation.
    """
    title           = models.CharField(max_length=120)
    slug            = models.SlugField(unique=True, blank=True)
    pub_date        = models.DateTimeField(default=timezone.now)
    tags            = models.CharField(max_length=240, blank=True, null=True)
    categories      = models.TextField(max_length=500, blank=True, null=True)

    @property
    def slides(self):
        """
        :return: a filter set of Slides, assigned to this SlideStack.
        """
        return Slide.objects.filter(slide_stack=self)

    @property
    def list_categories(self):
        """
        :return: a list of categories. Each element looks like follows: "Category_Topic"
        """
        if self.categories is not None:
            return [x.strip() for x in self.categories.split(',')]
        return []

    @property
    def list_category_tuples(self):
        """
        same method like list_categories() but return format is different.
        :return: a list of tuples. A tuple looks like follows: (Category, Topic)
        """
        if self.categories is not None:
            list_categories = [x.strip() for x in self.categories.split(',')]
            category_tuples = []
            for cat in list_categories:
                if not cat == '':
                    category_tuples.append(cat.split('_'))

            return category_tuples

        return []

    def __str__(self):
        return self.title

    def __repr__(self):
        return repr(self.id)

    def save(self, **kwargs):
        unique_slugify(self, self.title)
        super(SlideStack, self).save(**kwargs)


class Slide(models.Model):
    """
    This class represents a single slide. Each slide has a set of variables and is assigned to exactly one SlideStack.
    """
    def upload_location(instance, filename):
        return "slides/%s/%s" % (instance.slide_stack.slug, filename)

    title           = models.CharField(max_length=120)
    image           = models.ImageField(upload_to=upload_location)
    text_content    = models.TextField(blank=True, null=True)
    tags            = models.CharField(max_length=240, blank=True, null=True)
    slide_stack     = models.ForeignKey(SlideStack)

    def __str__(self):
        return self.title


class Structure:

    @staticmethod
    def create_structure():
        """
        This functionality checks all existing instances of SlideStack for categories and topics stored in
        categories field.
        :return: a list that contains lists. Each of the inner lists contains strings: the first element in the
        inner list is the category. All following elements in a inner list represent the topics allocated to the category
        """
        structure = []
        for slide_stack in SlideStack.objects.all():
            for tup in slide_stack.list_category_tuples:
                try:
                    inner_list = next(i for i in structure if i[0].strip().lower() == tup[0].strip().lower())

                    category = inner_list.pop(0)
                    try:
                        next(it for it in inner_list if it.strip().lower() == tup[1].strip().lower())
                    except StopIteration:
                        inner_list.append(tup[1])
                    inner_list.insert(0, category)

                except StopIteration:
                    structure.append([tup[0].strip(), tup[1].strip()])

        return structure

    structure = create_structure.__func__()

    @staticmethod
    def redefine_structure():
        """
        Refreshes Structure.structure after slides were added to the system.
        Should not be used, use DataStructure.redefine_data_structure() instead!
        """
        __class__.structure = __class__.create_structure()


class DataStructure:

    @staticmethod
    def create_data_structure():
        """
        This method uses the structure created with create_structure() and expands is with the matching data.
        :return: a complex data structure as follows: (String:category, [(String:topic title, [SlideStack])])
        """
        data_structure = []

        for lst in Structure.structure:
            category = lst.pop(0)

            topics = []
            for topic in lst:
                category_topic = category + '_' + topic
                slide_stacks = []
                for ss in SlideStack.objects.all():
                    if category_topic.lower() in (x.lower() for x in ss.list_categories):
                        slide_stacks.append(ss)

                topics.append((topic, slide_stacks))

            data_structure.append((category, topics))

        Structure.redefine_structure()
        return data_structure

    data_structure = create_data_structure.__func__()

    @staticmethod
    def redefine_data_structure():
        """
        Refreshes DataStructure.data_structure as well as Structure.structure.
        Use this method after adding slides to the system.
        :return:
        """
        __class__.data_structure = __class__.create_data_structure()
        Structure.redefine_structure()


def unique_slugify(instance, value, slug_field_name='slug', queryset=None,
                   slug_separator='-'):
    """
    Calculates and stores a unique slug of ``value`` for an instance.

    ``slug_field_name`` should be a string matching the name of the field to
    store the slug in (and the field to check against for uniqueness).

    ``queryset`` usually doesn't need to be explicitly provided - it'll default
    to using the ``.all()`` queryset from the model's default manager.
    """
    slug_field = instance._meta.get_field(slug_field_name)

    slug = getattr(instance, slug_field.attname)
    slug_len = slug_field.max_length

    # Sort out the initial slug, limiting its length if necessary.
    slug = slugify(value)
    if slug_len:
        slug = slug[:slug_len]
    slug = _slug_strip(slug, slug_separator)
    original_slug = slug

    # Create the queryset if one wasn't explicitly provided and exclude the
    # current instance from the queryset.
    if queryset is None:
        queryset = instance.__class__._default_manager.all()
    if instance.pk:
        queryset = queryset.exclude(pk=instance.pk)

    # Find a unique slug. If one matches, at '-2' to the end and try again
    # (then '-3', etc).
    next = 2
    while not slug or queryset.filter(**{slug_field_name: slug}):
        slug = original_slug
        end = '%s%s' % (slug_separator, next)
        if slug_len and len(slug) + len(end) > slug_len:
            slug = slug[:slug_len-len(end)]
            slug = _slug_strip(slug, slug_separator)
        slug = '%s%s' % (slug, end)
        next += 1

    setattr(instance, slug_field.attname, slug)


def _slug_strip(value, separator='-'):
    """
    Cleans up a slug by removing slug separator characters that occur at the
    beginning or end of a slug.

    If an alternate separator is used, it will also replace any instances of
    the default '-' separator with the new separator.
    """
    separator = separator or ''
    if separator == '-' or not separator:
        re_sep = '-'
    else:
        re_sep = '(?:-|%s)' % re.escape(separator)
    # Remove multiple instances and if an alternate separator is provided,
    # replace the default '-' separator.
    if separator != re_sep:
        value = re.sub('%s+' % re_sep, separator, value)
    # Remove separator from the beginning and end of the slug.
    if separator:
        if separator != '-':
            re_sep = re.escape(separator)
        value = re.sub(r'^%s+|%s+$' % (re_sep, re_sep), '', value)
    return value

src/slides/views.py
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.db.models import Q

from operator import attrgetter


# Create your views here.
from .models import Slide, SlideStack, Structure, DataStructure


def slides_contents(request):
    """
    :param request:
    :return: a view of all categories and their assigned topics.
    """

    context = {
        "structure": DataStructure.data_structure,
    }
    return render(request, "slides_overview.html", context)


def slide_topics(request, topic=None):
    """
    :param request:
    :param topic: the topic to be represented
    :return: shows all SlideStacks, which are assigned to the given topic.
    """

    used_slide_stacks = []
    for ss in SlideStack.objects.all():
        if topic.lower() in (x.lower() for x in ss.list_categories):
            used_slide_stacks.append(ss)

    # create next and previous link
    tup = topic.split('_')
    prev = ''
    nxt = ''
    for lst in Structure.structure:
        if lst[0] == tup[0]:
            chapt = lst.pop(0)
            i = lst.index(tup[1])
            if i > 0:
                prev = '/' + chapt + '_' + lst[i - 1]
            if len(lst) > i + 1:
                nxt = '/' + chapt + '_' + lst[i + 1]
            lst.insert(0, chapt)

    context = {
        "title": tup[1],
        "used_slide_stacks": used_slide_stacks,
        "prev": prev,
        "nxt": nxt,
        "top": topic,
    }

    return render(request, "slide_topics.html", context)


def slide_stack(request, topic=None, slug=None):
    """
    :param request:
    :param topic: defines the context. This is important for previous and next page functionality.
    :param slug: identifies the SlideStack to be displayed.
    :return: a view of all slides assigned to the SlideStack.
    """

    this_ss = get_object_or_404(SlideStack, slug=slug)

    # create next and previous link
    prev = ''
    nxt = ''
    if topic != 'none':
        ind = -1
        stop = False
        used_slide_stacks = []
        for ss in SlideStack.objects.all():
            if topic.lower() in (x.lower() for x in ss.list_categories):
                used_slide_stacks.append(ss)

                if stop:
                    break

                if ss.slug == slug:
                    ind = len(used_slide_stacks) - 1
                    stop = True

        if ind > 0:
            prev = reverse("slides:slidestack", kwargs={"topic": topic, "slug": used_slide_stacks[ind - 1].slug})
        if ind < len(used_slide_stacks) - 1:
            nxt = reverse("slides:slidestack", kwargs={"topic": topic, "slug": used_slide_stacks[ind + 1].slug})

    # find all other topics containing this SlideStack
    other_topics = []
    for cat in this_ss.list_category_tuples:
        if topic != cat[0] + '_' + cat[1]:
            other_topics.append(cat)

    context = {
        "title": this_ss.title,
        "other_topics": other_topics,
        "slides": this_ss.slides,
        "prev": prev,
        "nxt": nxt,
    }

    return render(request, "slide_stack.html", context)


def search(request):
    """
    Searches all SlideStacks and Slides for the given text
    :param request:
    :return: a view of all SlideStacks, which contain the search text
    in a variable, or has a Slide assigned that fits the search criteria.
    """

    title = 'nothing found'

    query = request.GET.get("q")
    if query:
        queryset_ss = SlideStack.objects.filter(
            Q(title__icontains=query) |
            Q(tags__icontains=query) |
            Q(categories__icontains=query)
        ).distinct()

        queryset_slides = Slide.objects.filter(
            Q(title__icontains=query) |
            Q(text_content__icontains=query) |
            Q(tags__icontains=query)
        ).distinct()

        if queryset_slides or queryset_ss:
            title = 'results found:'

        complete_set = set(queryset_ss)
        for slide in queryset_slides:
            complete_set.add(slide.slide_stack)

        complete_list = sorted(complete_set, key=attrgetter('id'), reverse=False)

    context = {
        "title": title,
        "found_slides": complete_list,
    }

    return render(request, "search.html", context)

src/slides/templates/base.html
{% load staticfiles %}
<!--DOCTYPE html -->
<html>
<head>

<title>{% block head_title %}Aurora Lite{% endblock head_title %}</title>
<!-- Bootstrap 4 -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/css/bootstrap.min.css" integrity="sha384-AysaV+vQoT3kOAXZkl02PThvDr8HYKPZhNT5h/CXfBThSRXQ6jW5DO2ekP5ViFdi" crossorigin="anonymous">
<link rel='stylesheet' href='{% static "css/custom.css" %}' />
<!-- Lightbox -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.0.0/ekko-lightbox.min.css" integrity="sha256-8aNQFtmxcOMVoOhLD4mrHqaKC2Ui++LmlQsoKTqxwIE=" crossorigin="anonymous" />
<!--FrameScrub -->
<link rel='stylesheet' href='{% static "css/frameScrub.css" %}' />
</head>
<body>


<div class='container'>
    {% block content %}{% endblock content %}
</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js" integrity="sha384-3ceskX3iaEnIogmQchP8opvBy3Mi7Ce34nWjpBIwVTHfGYWQS9jwHDVRnpKKHJg7" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.3.7/js/tether.min.js" integrity="sha384-XTs3FgkjiBgo8qjEjBk0tGmf3wPrWtA6coPfQDfFEY8AnYJwjalXCiosYRBIBZX8" crossorigin="anonymous"></script>
<!-- Bootstrap 4 -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/js/bootstrap.min.js" integrity="sha384-BLiI7JTZm+JWlgKa0M0kGRpJbF2J8q+qreVrKBC47e3K6BW78kGLrCkeRX6I9RoK" crossorigin="anonymous"></script>
<!-- Lightbox -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.0.0/ekko-lightbox.min.js" integrity="sha256-7Cjt+w+jZgmYnx3j2lZ7lOjbEHm4RdflVPClpK5+eHg=" crossorigin="anonymous"></script>
<script type="text/javascript">
    $(document).on('click', '[data-toggle="lightbox"]', function(event) {
    event.preventDefault();
    $(this).ekkoLightbox();
});
</script>

<script src="{% static "js/frameScrub.js" %}"></script>
<script>
    $(document).ready(function () {
        setFrameScrubHeight();
    });
    $(window).resize(function () {
        setFrameScrubHeight();
    });
    function setFrameScrubHeight() {
        var cw = $('.fs').width();
        $('.fs').css({
            'height': cw * .5625 + 'px'
        });
    }
    $(".fs").frameScrub({
      defaultImage: 'firstImage',
      verticalAlignment: 'top'
    });
  </script>
</body>
</html>

src/slides/templates/search.html
{% extends "base.html" %}
{% load thumbnail %}
{% block content %}


<div class="row">
<div class="col-xs-12">
    <form method="GET" action="" class="text-xs-right">
    <input type="text" name="q" placeholder="Search slides" value="{{ request.GET.q }}"/>
    <input type="submit" value="Search" />
    </form>
</div>
</div>

<h3>{{ title }}</h3>
<hr />

<div class="row">
{% for slide_stack in found_slides %}

  <div class="col-xs-12 col-md-6 col-xl-4">
    <div class="card card-block">
    <a href="{% url 'slides:slidestack' topic='none' slug=slide_stack.slug %}">
        <div id="fs{{ forloop.counter }}" class="fs" style="width:100%;height:100px;overflow:hidden;">

            <img class="card-img-top" src="{{ slide_stack.slides.0.image|thumbnail_url:'preview' }}" id="firstImage" />
            {% for slide in slide_stack.slides %}
                {% if not forloop.first %}

                    <img class="card-img-top img-fluid" src="{{ slide.image|thumbnail_url:'preview' }}" />

                {% endif %}
            {% endfor %}
        </div>
    </a>

        <p></p>
        <h3 class="card-title">{{ slide_stack.title }}</h3>
        <a href="{% url 'slides:slidestack' topic='none' slug=slide_stack.slug %}" class="btn btn-primary">View Slides</a>


    </div>
  </div>

{%  endfor %}
</div>


{% endblock content %}

src/slides/templates/slide_stack.html
{% extends "base.html" %}
{% load thumbnail %}
{% block content %}



<h1>{{ title }}</h1>
    <p>this slides are found in:
        {% for topic in other_topics %}
            <a href="/{{ topic.0 }}_{{ topic.1 }}">{{ topic.0 }}: {{ topic.1 }}</a>{% if not forloop.last %},{% endif %}
        {% endfor %}
    </p>
<hr />

<div class="row">
{% for slide in slides %}

<div class="col-xs-12 col-md-6 col-xl-4">
    <div class="card card-block">
        <a href="{{ slide.image|thumbnail_url:'full-res' }}" data-toggle="lightbox" data-gallery="example-gallery">
        <img src="{{ slide.image|thumbnail_url:'preview' }}" class="img-fluid" alt="" />
        </a>
        <p></p>
        <h3 class="card-title">{{ slide.title }}</h3>
    </div>
</div>
{% endfor %}
</div>
    <hr />

<div class="row">
    <div class="col-xs-6">
    <p class="text-xs-left"><a href="{{ prev }}" class="btn-prev">prev</a></p>
        </div>
    <div class="col-xs-6">
    <p class="text-xs-right"><a href="{{ nxt }}" class="btn-next">next</a></p>
    </div>
</div>



{% endblock content %}

src/slides/templates/slide_topics.html
{% extends "base.html" %}
{% load thumbnail %}
{% block content %}



<h1>{{ title }}</h1>
<hr />

<div class="row">
{% for slide_stack in used_slide_stacks %}

  <div class="col-xs-12 col-md-6 col-xl-4">
    <div class="card card-block">
    <a href="{% url 'slides:slidestack' topic=top slug=slide_stack.slug %}">
        <div id="fs{{ forloop.counter }}" class="fs" style="width:100%;height:100px;overflow:hidden;">

            <img class="card-img-top" src="{{ slide_stack.slides.0.image|thumbnail_url:'preview' }}" id="firstImage" />
            {% for slide in slide_stack.slides %}
                {% if not forloop.first %}

                    <img class="card-img-top img-fluid" src="{{ slide.image|thumbnail_url:'preview' }}" />

                {% endif %}
            {% endfor %}
        </div>
    </a>

    <p></p>
    <h3 class="card-title">{{ slide_stack.title }}</h3>
    <a href="{% url 'slides:slidestack' topic=top slug=slide_stack.slug %}" class="btn btn-primary">View Slides</a>

    </div>
  </div>

{%  endfor %}
</div>
<hr />

<div class="row">
    <div class="col-xs-6">
    <p class="text-xs-left"><a href="{{ prev }}" class="btn-prev">prev</a></p>
        </div>
    <div class="col-xs-6">
    <p class="text-xs-right"><a href="{{ nxt }}" class="btn-next">next</a></p>
    </div>
</div>



{% endblock content %}

src/slides/templates/slides_overview.html
{% extends "base.html" %}
{% load thumbnail %}
{% block content %}



<div class="row">
<div class="col-xs-12">
    <form method="GET" action="{% url 'slides:search' %}" class="text-xs-right">
    <input type="text" name="q" placeholder="Search slides"/>
    <input type="submit" value="Search" />
    </form>
</div>
</div>

{% for category in structure %}
    <h1>{{ category.0 }}</h1>
    <hr />

    <div class="row">

    {% for topic in category.1 %}
        <div class="col-xs-12 col-md-6 col-xl-4">
            <div class="card card-block">
              <a href="/{{ category.0 }}_{{ topic.0 }}">
              <div id="fs{{ forloop.counter }}" class="fs" style="width:100%;height:50px;overflow:hidden;">

                <img class="card-img-top" src="{{ topic.1.0.slides.0.image|thumbnail_url:'preview' }}" id="firstImage" />
                {% for slide_stack in topic.1 %}
                    {% if not forloop.first %}
                    <img class="card-img-top img-fluid" src="{{ slide_stack.slides.0.image|thumbnail_url:'preview' }}" />
                    {% endif %}
                {% endfor %}
              </div>
              </a>
              <p></p>
              <h3 class="card-title">{{ topic.0 }}</h3>
              <p class="card-text">{{ topic.1.0.image.src }}</p>
              <a href="/{{ category.0 }}_{{ topic.0 }}" class="btn btn-primary">View Topic</a></p>
            </div>
        </div>
    {% endfor %}

    </div>
    <br />

{% endfor %}



{% endblock content %}